name: test Go using asdf

on:
  push:
  pull_request:

jobs:
  test-asdf:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install asdf & tools
        uses: asdf-vm/actions/install@v2

      - name: Tests
        run: go test -v ./...
